name: car_parts

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    networks:
      - default
    depends_on:
      php:
        condition: service_started

  php:
    build: 
      args:
        user: user1
        uid: 1000
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 3000:3000
    expose: 
      - 9000
    networks:
      - default
    depends_on:
      mysql:
        condition: service_started

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_DATABASE: car_parts
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - default
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    networks:
      - default
    depends_on:
      mysql:
        condition: service_started

networks:
  default:
    driver: bridge